### PR TITLE
Update Profile for Vedant

### PR DESCRIPTION
**Pull request by 007vedant**

### CODE REVIEW

**Comment by DesignrKnight** [comment]
@SriramPatibanda 
I suppose the edit is in the wrong file. Can you confirm?

**Comment by SriramPatibanda** [comment]
> @SriramPatibanda
> I suppose the edit is in the wrong file. Can you confirm?

Yeah, for adding your profile to the team, you must make changes in the public/team.html by adding your photo, name and stack.

**Comment by DesignrKnight** [comment]
Also @SriramPatibanda , there are 17 branches in the repo. Can you delete the ones that are no longer needed

**Comment by 007vedant** [comment]
> I suppose the edit is in the wrong file. Can you confirm?
Sorry. I thought I was required to add the profile in the Submissions section. (Readme)

**Review by DesignrKnight — APPROVED** [review]

**Comment by DesignrKnight** [comment]
Damn, that was to release branch.

**Pull request merged**
