### PR TITLE
Configured the Repo with Starter Template

### PR DESCRIPTION
**Pull request by abhibhaw**

### CODE REVIEW

**Comment by abhibhaw** [comment]
@HarishTeens There is no release branch, But release branch refereed in Readme

**Comment by abhibhaw** [comment]
@HarishTeens Also install all contributors bot before merging 🤣

**Comment by HarishTeens** [comment]
@all-contributors please add @HarishTeens for code

**Comment by abhibhaw** [comment]
@all-contributors please add @abhibhaw  for Readme

**Comment by abhibhaw** [comment]
@all-contributors please add @abhibhaw for documentation

**Comment by abhibhaw** [comment]
@all-contributors please add @DesignrKnight for code

**Comment by abhibhaw** [comment]
@all-contributors please add @roshankshaw for code

**Comment by abhibhaw** [comment]
@all-contributors please add @ritomsonowal for code

**Comment by abhibhaw** [comment]
@all-contributors please add @SriramPatibanda for code

**Comment by abhibhaw** [comment]
@all-contributors please add @prachi237 for code

**Comment by abhibhaw** [comment]
@all-contributors please add @ORKO06 for code

**Comment by abhibhaw** [comment]
@all-contributors please add @Veen-18 @007vedant for code

**Comment by abhibhaw** [comment]
@all-contributors please add @bgov600 for code

**Comment by abhibhaw** [comment]
@all-contributors please add @JaiNITR  for code

**Comment by abhibhaw** [comment]
@all-contributors please add @varnika18 for code

**Comment by abhibhaw** [comment]
@all-contributors please add @mk15012 for code

**Comment by abhibhaw** [comment]
@all-contributors please add @dsc-nitr for code

**Comment by abhibhaw** [comment]
@all-contributors please add @tanishq12442 for code

**Comment by abhibhaw** [comment]
@all-contributors please add @ashsek for code

**Comment by abhibhaw** [comment]
@all-contributors please add @CIPHERTron for code

**Comment by abhibhaw** [comment]
@all-contributors please add @rohitk2001 for code

**Comment by abhibhaw** [comment]
@all-contributors please add @pao0318 for code

**Comment by abhibhaw** [comment]
@all-contributors please add @malayaj2000 for code

**Review by HarishTeens — APPROVED** [review]

**Pull request merged**
